export const ErrorCodes = {
  // Аутентификация и авторизация
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_GENERATION_FAILED: 'TOKEN_GENERATION_FAILED',
  TOKEN_VERIFICATION_FAILED: 'TOKEN_VERIFICATION_FAILED',
  
  // Пользователи
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_CREATION_FAILED: 'USER_CREATION_FAILED',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  NICKNAME_EXISTS: 'NICKNAME_EXISTS',
  
  // Пароли
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  PASSWORD_HASHING_FAILED: 'PASSWORD_HASHING_FAILED',
  
  // Валидация
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_INPUT: 'INVALID_INPUT',
  
  // Общие ошибки
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  
  // Куки и сессии
  COOKIE_SET_FAILED: 'COOKIE_SET_FAILED',
  COOKIE_CLEAR_FAILED: 'COOKIE_CLEAR_FAILED',
  
  // Восстановление паролей
  RECOVERY_CODE_INVALID: 'RECOVERY_CODE_INVALID',
  RECOVERY_CODE_EXPIRED: 'RECOVERY_CODE_EXPIRED',
  
  // Аутентификация
  LOGIN_FAILED: 'LOGIN_FAILED',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED'
} as const;